/**
 * @file Run Axe accessibility tests on pages generated by drupal templates with Nightwatch.
 */

const axeOptions = {
    timeout: 500,
    runOnly: {
        type: 'tag',
        values: ['wcag2a'], //, 'wcag2aa'
    },
    verbose: true,
    reporter: 'v2',
    elementRef: true,
    abortOnAssertionFailure: false,
    end_session_on_fail: false,
    skip_testcases_on_fail: true,
};

const dev = "http://localhost:3001";
const siteUrl = dev;

const contextOptions = {
    include: [['body']],
    exclude: [['#content'], ['#behavior'], ['.hidden']]
}

const exclusions = {
    exclude: [['#content'], ['#behavior']]
}

const drupalurls = [['/drupal/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services/index.html'],
    ['/drupal/pension/index.html'],
    ['/drupal/pittsburgh-health-care/locations/university-drive-medical-center/index.html']
];

function testUrl(browser, url) {
    browser
        .url(url)
        .waitForElementVisible('body', 6000)
        .initAccessibility()
        .verify.accessibility(contextOptions, axeOptions)
        .end(function(err, res){
            console.log(res);
        });
}

module.exports
    = {
    '@tags': ['accessibility', 'templates'],

    'Test templates 1': function (browser) {
        testUrl(browser, siteUrl + '/drupal/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services/index.html');
    },
    'Test templates 2': function (browser) {
        testUrl(browser, siteUrl + '/drupal/pension/index.html');
    }
}

